steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'mcps/dynamic_prompt/infra/Dockerfile'
      - '-t'
      - '${_IMAGE}'
      - '.'
images:
  - '${_IMAGE}'
